[package]
name = "er-rusted"
version = "0.1.0"
authors = ["eulegang <eulegang@eulegang.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
regex = "1"
nom = "6"

rustyline = "7.0"
rustbox = "0.11"
