[package]
name = "er-rusted"
version = "0.1.0"
authors = ["eulegang <eulegang@eulegang.dev>"]
edition = "2018"

[dependencies]
eyre = "0.6"
regex = "1"
nom = "6"
structopt = "0.3"
rustyline = "7.0"
atty = "0.2"
crossterm = "0.19"
